'use strict';
(async()=>{
 let entries=[],map=null,markers=new Map(),point=null,filter='all',query='',selectedId=null,favorites=new Set();
 function note(text){$('#map-message').textContent=text;$('#map-message').hidden=false;}
 function distance(a,b){const rad=v=>v*Math.PI/180,dLat=rad(b[0]-a[0]),dLng=rad(b[1]-a[1]);return 6371*2*Math.atan2(Math.sqrt(Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLng/2)**2),Math.sqrt(1-(Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLng/2)**2)));}
 function select(id){selectedId=id;draw();const s=entries.find(s=>s.id===id);if(map&&s?.point){map.panTo(s.point);markers.get(id)?.openTooltip();}}
 function draw(){let list=entries.filter(s=>(s.name+' '+s.city+' '+s.specialties.join(' ')).toLowerCase().includes(query));if(filter==='nearest'&&point)list.sort((a,b)=>(a.distance??Infinity)-(b.distance??Infinity));
  $('#matching-studios').innerHTML=list.length?list.map(s=>'<article class="studio-card '+(s.id===selectedId?'selected':'')+'" data-select="'+s.id+'" tabindex="0" aria-label="'+escapeHTML(s.name)+'"><div class="studio-photo" style="display:grid;place-items:center;background:#fbe0e9;font-size:34px;color:#a85171">'+escapeHTML(s.name.charAt(0))+'</div><div class="studio-card-copy"><h2>'+escapeHTML(s.name)+'</h2><p>'+escapeHTML(s.city)+(Number(s.is_demo)?' · Sample listing':'')+'</p><p class="studio-distance">'+(s.distance!==null?s.distance.toFixed(1)+' km away':s.point?'Location available on map':'Map location not provided')+'</p><div class="studio-tags">'+s.specialties.map(t=>'<span>'+escapeHTML(t)+'</span>').join('')+'</div></div><div class="studio-card-actions"><button class="favorite-studio" data-favorite="'+s.id+'" aria-label="Save '+escapeHTML(s.name)+'" aria-pressed="'+favorites.has(s.id)+'"><svg><use href="#heart"/></svg></button><button class="select-studio" data-focus="'+s.id+'" aria-label="View studio details"><svg><use href="#arrow"/></svg></button></div></article>').join(''):'<p class="empty">No Cavite studios found. Try another city or lash style.</p>';
  $$('[data-select]').forEach(card=>{card.onclick=()=>showDetail(Number(card.dataset.select));card.onkeydown=e=>{if(e.target===card&&['Enter',' '].includes(e.key)){e.preventDefault();showDetail(Number(card.dataset.select));}};});
  $$('[data-focus]').forEach(b=>b.onclick=e=>{e.stopPropagation();showDetail(Number(b.dataset.focus));});
  $$('[data-favorite]').forEach(b=>b.onclick=async e=>{e.stopPropagation();b.disabled=true;const id=Number(b.dataset.favorite),next=new Set(favorites);next.has(id)?next.delete(id):next.add(id);try{await SavedItems.save('studios',user.id,[...next]);favorites.clear();next.forEach(id=>favorites.add(id));draw();}catch(error){toast(error.message);b.disabled=false;}});
 }
 const showDetail=window.createStudioDetail({entries,select,favorites,draw});
 function initMap(){if(!window.L){note('The map could not load. Studio listings are still available.');return;}map=L.map('studio-map',{scrollWheelZoom:false}).setView([14.28,120.87],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map).on('tileerror',()=>note('Map tiles are unavailable. Studio listings are still available.'));for(const s of entries){if(!s.point)continue;const label=document.createElement('span');label.textContent=s.name;markers.set(s.id,L.marker(s.point).addTo(map).bindTooltip(label).on('click',()=>select(s.id)));}if(markers.size)map.fitBounds([...markers.values()].map(m=>m.getLatLng()),{padding:[30,30],maxZoom:14});else note('No Cavite studio locations are available yet.');new ResizeObserver(()=>map.invalidateSize()).observe($('#studio-map'));}
 async function load(){try{const session=await api('session');if(!session.user){location.replace('login.html');return;}user=session.user;csrf=session.csrf;const state=ProfileData.summary(user.id);$$('.studio-progress li').forEach((step,index)=>step.classList.toggle('done',index<4?state.quizCount>0:index===4?state.triedOn:false));const r=await api('studios');entries.splice(0,entries.length,...r.studios.map(s=>({...s,point:s.latitude!==null&&s.longitude!==null?[Number(s.latitude),Number(s.longitude)]:null,distance:null})));favorites=new Set(SavedItems.list('studios',user.id));
   // Keep the set passed to the detail view in sync through its context.
   detailFavorites.clear();favorites.forEach(id=>detailFavorites.add(id));favorites=detailFavorites;
   $('#greeting').textContent='Hi, '+user.name.split(' ')[0]+'!';$('#avatar').textContent=user.name.charAt(0).toUpperCase();$('#studio-loading').hidden=true;$('#studio-results').hidden=false;draw();initMap();const id=location.hash.match(/^#studio-(\d+)$/);if(id)showDetail(Number(id[1]),false);
  }catch(e){$('#studio-loading').innerHTML='<p class="empty">'+escapeHTML(e.message)+' <a href="Fstudios.html">Retry</a></p>';}}
 const detailFavorites=favorites;
 $$('[data-filter]').forEach(b=>{if(b.dataset.filter==='rating'){b.disabled=true;b.title='Ratings have not been collected yet.';}b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();};});
 function search(value){query=value.trim().toLowerCase();draw();}
 $('#area-search').onsubmit=e=>{e.preventDefault();search($('#area-query').value);};$('#dashboard-search').onsubmit=e=>{e.preventDefault();search($('#home-search').value);};$('#area-query').oninput=e=>search(e.target.value);
 $('#map-center').onclick=()=>{if(map)map.setView(point||[14.28,120.87],12);};
 $('#current-location').onclick=()=>{if(!navigator.geolocation){note('Location is unavailable in this browser.');return;}note('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{point=[p.coords.latitude,p.coords.longitude];for(const s of entries)s.distance=s.point?distance(point,s.point):null;if(map){L.circleMarker(point,{radius:7}).addTo(map).bindTooltip('Your location');map.setView(point,12);}note('Distances are straight-line estimates from your location.');draw();},()=>note('Location permission was unavailable. Search by city instead.'),{timeout:8000});};
 $('#studio-edit').onclick=()=>location.assign('tryon.html');$$('[data-quiz]').forEach(b=>b.onclick=()=>location.assign('preference.html'));$$('[data-results]').forEach(b=>b.onclick=()=>location.assign('home.html#results'));$$('[data-saved]').forEach(b=>b.onclick=()=>location.assign('saved.html'));$('#notifications').onclick=()=>open('<h2>Notifications</h2><p>You have no new notifications.</p>');
 load();
})();
addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
