'use strict';
let preferenceStep=0,preferenceAnswers={},preferenceUser=null,preferenceCropId=0;
function preferenceImage(box,fit='meet',source='ref3.png'){const [x,y,w,h]=box.split(' ').map(Number),id='pref-crop-'+(++preferenceCropId);return '<svg viewBox="'+box+'" preserveAspectRatio="xMidYMid '+fit+'" aria-hidden="true"><defs><clipPath id="'+id+'"><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'"/></clipPath></defs><image href="'+source+'" width="'+(source==='ref4.png'?1429:1620)+'" height="'+(source==='ref4.png'?953:1080)+'" clip-path="url(#'+id+')"/></svg>';}
$('.sidebar-art').innerHTML=preferenceImage('0 680 290 355');$('.preference-decoration').innerHTML=preferenceImage('1198 87 231 866','slice','ref4.png');
const preferencePhotos=['355 450 215 155','612 450 215 155','865 450 213 155','1118 450 212 155'];
const preferenceSteps=[
 {key:'experience',title:'How often do you usually wear lash extensions?',description:'Choose the option that best describes your experience.',source:'ref4.png',photos:['365 445 115 100','588 445 115 100','811 445 115 100','1034 445 115 100'],options:[['first-time','First Time','This will be my first lash extension experience.'],['occasionally','Occasionally','I wear lash extensions only from time to time.'],['regularly','Regularly','Lash extensions are part of my usual beauty routine.'],['very-often','Very Often','I regularly maintain and refresh my lash extensions.']]},
 {key:'volume',title:'What volume do you prefer?',description:'Choose the option that best matches your desired fullness.',source:'ref3.png',photos:['352 442 214 155','609 442 214 155','865 442 213 155','1119 442 211 155'],options:[['light','Light','A subtle enhancement with a natural feel.'],['medium','Medium','A balanced, noticeable look without being too dramatic.'],['full','Full','A voluminous and dramatic look.'],['mega','Mega Volume','Maximum fullness for a bold statement look.']]},
 {key:'occasion',title:'What is the main occasion for your lash look?',description:'Choose the option that best fits your lifestyle.',source:'ref5.png',photos:['344 438 222 162','600 438 223 162','857 438 222 162','1107 438 222 162'],options:[['everyday','Everyday','For work, school, or just daily activities.'],['event','Special Events','For parties, weddings, or formal occasions.'],['travel','Vacation / Travel','For trips, beach days, or outdoor activities.'],['night','Night Out','For dates, nightlife, or a more bold look.']]},
 {key:'finish',title:'Here\u2019s Your Perfect Match!',description:'Based on your answers, we\u2019ve found the lash style that suits you best.',options:[]}
];
function rememberPreference(){try{sessionStorage.setItem('lashmatch-quiz-'+preferenceUser.id,JSON.stringify(preferenceAnswers));}catch{}}
function drawPreference(){const step=preferenceSteps[preferenceStep];document.body.classList.toggle('finish-step',preferenceStep===3);$('#quiz-next').onclick=null;$('#quiz-next').disabled=false;document.body.classList.toggle('experience-step',step.key==='experience');document.body.classList.toggle('volume-step',step.key==='volume');document.body.classList.toggle('occasion-step',step.key==='occasion');$('#question-title').textContent=step.title;$('#question-description').textContent=step.description;$('.preference-options').innerHTML=step.options.map((option,i)=>'<label class="preference-option"><span class="option-photo">'+preferenceImage((step.photos||preferencePhotos)[i],'meet',step.source||'ref3.png')+'</span><strong>'+escapeHTML(option[1])+'</strong><span class="description">'+escapeHTML(option[2])+'</span><input type="radio" name="choice" value="'+option[0]+'" aria-label="'+escapeHTML(option[1])+'" '+(preferenceAnswers[step.key]===option[0]?'checked':'')+' required></label>').join('');renderQuizProgress(preferenceStep);$('#quiz-next span').textContent=preferenceStep===3?'View in Virtual Try-On':'Next';$('#quiz-message').textContent='';$$('[name=choice]').forEach(input=>input.onchange=()=>{preferenceAnswers[step.key]=input.value;rememberPreference();});if(preferenceStep===3)drawFinish();}
$('#quiz-back').onclick=()=>{if(preferenceStep===0){location.assign('home.html');return;}preferenceStep--;drawPreference();};
$('#preference-form').onsubmit=event=>{event.preventDefault();if(preferenceStep===3)return;const checked=$('[name=choice]:checked');if(!checked)return;preferenceAnswers[preferenceSteps[preferenceStep].key]=checked.value;rememberPreference();if(preferenceStep<3){preferenceStep++;drawPreference();$('#question-title').focus();return;}const answers={eye_shape:'unsure',finish:preferenceAnswers.finish,occasion:['event','night'].includes(preferenceAnswers.occasion)?'event':'everyday'};showResult(answers);try{sessionStorage.setItem('lashmatch-result-'+preferenceUser.id,JSON.stringify(answers));}catch{}};
$$('[data-quiz]').forEach(b=>b.onclick=()=>{preferenceStep=0;drawPreference();});$$('[data-results]').forEach(b=>b.onclick=()=>location.assign('home.html#results'));$$('[data-saved]').forEach(b=>b.onclick=()=>location.assign('saved.html'));$$('[data-profile]').forEach(b=>b.onclick=()=>{showAccount();$('#logout').onclick=async()=>{try{await api('logout',{});location.replace('login.html');}catch(error){$('.message',content).textContent=error.message;}};});$('#notifications').onclick=()=>open('<h2>Notifications</h2><p>You have no new notifications.</p>');$('#dashboard-search').onsubmit=event=>{event.preventDefault();showStudios();};
async function loadPreference(){try{const session=await api('session');if(!session.user){location.replace('login.html');return;}user=session.user;preferenceUser=user;csrf=session.csrf;$('#greeting').textContent='Hi, '+user.name.split(' ')[0]+'!';$('#avatar').textContent=user.name.charAt(0).toUpperCase();try{const saved=JSON.parse(sessionStorage.getItem('lashmatch-quiz-'+user.id)||'{}');if(typeof saved.resultSignature==='string'&&typeof saved.requestKey==='string'&&/^[a-zA-Z0-9-]{8,64}$/.test(saved.requestKey)){preferenceAnswers.resultSignature=saved.resultSignature;preferenceAnswers.requestKey=saved.requestKey;}for(const step of preferenceSteps){if(step.options.some(o=>o[0]===saved[step.key]))preferenceAnswers[step.key]=saved[step.key];}}catch{}if(location.hash==='#finish'&&preferenceAnswers.experience&&preferenceAnswers.volume&&preferenceAnswers.occasion)preferenceStep=3;drawPreference();$('.dashboard').hidden=false;$('#session-status').hidden=true;}catch{$('#session-status').innerHTML='<div><p>Unable to load your quiz.</p><button class="button" id="retry-preference">Retry</button></div>';$('#retry-preference').onclick=loadPreference;}}
loadPreference();
