'use strict';
window.createStudioDetail=function({entries,select,favorites,draw}){
 const host=document.createElement('section');host.id='studio-detail';host.hidden=true;host.setAttribute('aria-label','Studio details');document.querySelector('.studios-content').append(host);
 function back(){host.hidden=true;document.body.classList.remove('viewing-studio');document.querySelector('#studio-results').hidden=false;history.replaceState(null,'',location.pathname);}
 function display(id,push=true){const s=entries.find(s=>s.id===id);if(!s)return;if(push)history.pushState(null,'','#studio-'+id);document.querySelector('#studio-results').hidden=true;host.hidden=false;document.body.classList.add('viewing-studio');
  host.innerHTML='<div class="detail-heading"><button class="detail-back" id="detail-back">← Back to Results</button><h1 tabindex="-1">'+escapeHTML(s.name)+'</h1><p class="detail-address">'+escapeHTML(s.address||s.city)+'</p><div class="detail-tags">'+s.specialties.map(t=>'<span>'+escapeHTML(t)+'</span>').join('')+'</div><div class="detail-tools"><button id="detail-save" aria-pressed="'+favorites.has(id)+'">'+(favorites.has(id)?'Saved Studio':'Save Studio')+'</button><button id="detail-share">Copy link</button></div></div><div class="detail-left"><section class="detail-about"><h2>About this studio</h2><p>'+escapeHTML(s.description||'No description has been added yet.')+'</p>'+(Number(s.is_demo)?'<p>This is a sample listing.</p>':'')+'</section></div><aside class="detail-right"><section class="detail-contact"><h3>Contact Information</h3><p>Phone: '+escapeHTML(s.phone||'Not provided')+'</p><p>Instagram: '+escapeHTML(s.instagram||'Not provided')+'</p><p>Facebook: '+escapeHTML(s.facebook||'Not provided')+'</p><p>'+escapeHTML(s.address||s.city)+'</p></section></aside><div class="detail-bottom"><button id="detail-map" '+(!s.point?'disabled':'')+'>View on Map</button></div>';
  document.querySelector('#detail-back').onclick=back;document.querySelector('#detail-map').onclick=()=>{back();select(id);document.querySelector('#studio-map').scrollIntoView({block:'center'});};
  document.querySelector('#detail-save').onclick=async e=>{const button=e.target;button.disabled=true;const next=new Set(favorites);next.has(id)?next.delete(id):next.add(id);try{await SavedItems.save('studios',user.id,[...next]);favorites.clear();next.forEach(x=>favorites.add(x));button.textContent=favorites.has(id)?'Saved Studio':'Save Studio';button.setAttribute('aria-pressed',String(favorites.has(id)));draw();}catch(error){toast(error.message);}finally{button.disabled=false;}};
  document.querySelector('#detail-share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Studio link copied.');}catch{toast('Copy the address from your browser to share this studio.');}};
  host.querySelector('h1').focus();
 }
 addEventListener('popstate',()=>{const match=location.hash.match(/^#studio-(\d+)$/);if(match)display(Number(match[1]),false);else back();});return display;
};
