<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/db.php';
$db=database();$tag='integration-'.bin2hex(random_bytes(6));$password=bin2hex(random_bytes(12));$ids=[];$studioId=null;$extraStyleId=null;
$cookies=[];$tokens=[];$checks=0;
function check(bool $ok,string $label): void {global $checks;if(!$ok)throw new RuntimeException($label);$checks++;echo "PASS $label\n";}
function callApi(string $who,string $action,?array $body=null,?string $token=null): array {
 global $cookies,$tokens;
 $cookies[$who]??=tempnam(sys_get_temp_dir(),'lash-check-');
 $ch=curl_init((getenv('LASHMATCH_TEST_URL') ?: 'http://localhost:8080').'/api.php?action='.$action);
 curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIEFILE=>$cookies[$who],CURLOPT_COOKIEJAR=>$cookies[$who],CURLOPT_TIMEOUT=>10]);
 if($body!==null)curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($body),CURLOPT_HTTPHEADER=>['Content-Type: application/json','X-CSRF-Token: '.($token??$tokens[$who]??'')]]);
 $raw=curl_exec($ch);if($raw===false)throw new RuntimeException(curl_error($ch));$status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);
 $data=json_decode($raw,true,512,JSON_THROW_ON_ERROR);if(isset($data['csrf']))$tokens[$who]=$data['csrf'];return [$status,$data];
}
$originalRules=$db->query('SELECT volume,finish FROM recommendation_rules')->fetchAll(PDO::FETCH_KEY_PAIR);
$originalStyle=$db->query("SELECT id,description FROM lash_styles WHERE name='Classic'")->fetch();
try{
 check(callApi('guest','admin_data')[0]===401,'guest cannot read admin records');
 callApi('client','session');[$code,$client]=callApi('client','signup',['name'=>'Integration Client','email'=>$tag.'@example.com','password'=>$password,'role'=>'admin']);
 check($code===201 && $client['user']['role']==='user','signup cannot grant admin privileges');$ids[]=$client['user']['id'];$clientId=$client['user']['id'];
 [, $empty]=callApi('client','session');
 check($empty['saved']['looks']===[] && $empty['saved']['studios']===[],'new account has no favorites');
 check($empty['journey']===['quizCount'=>0,'triedOn'=>false,'events'=>[]],'new account has no progress or activity');
 check(callApi('client','matches')[1]['matches']===[],'new account has no quiz results');
 check(callApi('guest','record_tryon',[])[0]===403,'try-on recording requires CSRF');
 check(callApi('client','record_tryon',['request_key'=>'bad'])[0]===422,'try-on request is validated');
 check(callApi('client','record_tryon',['request_key'=>$tag])[0]===200,'completed try-on saved');
 callApi('client','record_tryon',['request_key'=>$tag]);
 [, $progress]=callApi('client','session');
 check($progress['journey']['triedOn'] && count($progress['journey']['events'])===1,'try-on retries do not duplicate activity');
 check(callApi('client','admin_data')[0]===403,'client cannot read admin records');
 check(callApi('client','admin_rules_save',['rules'=>$originalRules])[0]===403,'client cannot change recommendation rules');
 check(callApi('client','save_match',['eye_shape'=>'almond','finish'=>'balanced','occasion'=>'everyday'],'wrong')[0]===403,'CSRF token is required');
 $db->prepare("INSERT INTO users(name,email,password_hash,role) VALUES (?,?,?,'admin')")->execute(['Integration Admin',$tag.'-admin@example.com',password_hash($password,PASSWORD_DEFAULT)]);$ids[]=(int)$db->lastInsertId();
 callApi('admin','session');[$code,$admin]=callApi('admin','login',['email'=>$tag.'-admin@example.com','password'=>$password,'role'=>'admin']);check($code===200 && $admin['user']['role']==='admin','administrator can sign in');
 $rules=$originalRules;$rules['light']='textured';check(callApi('admin','admin_rules_save',['rules'=>$rules])[0]===200,'admin updates recommendation rules');
 $answers=['eye_shape'=>'unsure','volume'=>'light','experience'=>'first-time','occasion'=>'everyday','request_key'=>$tag];
 [$code,$match]=callApi('client','save_match',$answers);check($code===201 && $match['style']==='Wispy','client quiz uses admin rule');
 [$code,$repeat]=callApi('client','save_match',$answers);check($code===200 && $repeat['id']===$match['id'],'retry does not duplicate quiz result');
 [$code,$history]=callApi('client','matches');check($code===200 && count($history['matches'])===1,'client can reload saved quiz result');
 $studio=['name'=>$tag.' <studio>','city'=>'Imus','address'=>'Test Address','description'=>'Integration test only','specialties'=>['Wispy'],'latitude'=>14.4297,'longitude'=>120.9367,'is_active'=>true,'is_demo'=>true,'phone'=>'','instagram'=>'','facebook'=>''];
 check(callApi('admin','admin_studio_save',array_replace($studio,['city'=>'Manila']))[0]===422,'outside-Cavite studio is rejected');
 check(callApi('admin','admin_studio_save',array_replace($studio,['city'=>'Manila, Cavite']))[0]===422,'adding Cavite suffix cannot bypass city validation');
 [$code,$created]=callApi('admin','admin_studio_save',$studio);check($code===200,'administrator creates studio');$studioId=$created['id'];
 [$code,$directory]=callApi('client','studios');check(count(array_filter($directory['studios'],fn($s)=>$s['id']===$studioId && $s['name']===$studio['name']))===1,'admin studio appears in client directory');
 $db->prepare('UPDATE studios SET city=? WHERE id=?')->execute(['Manila',$studioId]);
 [, $outside]=callApi('client','studios');
 check(!array_filter($outside['studios'],fn($s)=>$s['id']===$studioId),'legacy outside-Cavite studio is hidden');
 check(callApi('client','save_favorites',['kind'=>'studios','items'=>[$studioId]])[0]===422,'outside-Cavite studio cannot be saved');
 $db->prepare('UPDATE studios SET city=? WHERE id=?')->execute(['Imus',$studioId]);
 check(callApi('client','save_favorites',['kind'=>'studios','items'=>[$studioId]])[0]===200,'client saves studio to MySQL');
 check(callApi('client','save_favorites',['kind'=>'looks','items'=>['Wispy']])[0]===200,'client saves lash look to MySQL');
 [$code,$snapshot]=callApi('admin','admin_data');
 check(count(array_filter($snapshot['users'],fn($u)=>(int)$u['id']===$clientId))===1,'client account visible in admin');
 check(count(array_filter($snapshot['matches'],fn($m)=>(int)$m['user_id']===$clientId && $m['style']==='Wispy'))===1,'client result visible in admin');
 check(count(array_filter($snapshot['saved'],fn($s)=>(int)$s['user_id']===$clientId))===2,'client favorites visible in admin');
 $studio['id']=$studioId;$studio['is_active']=false;check(callApi('admin','admin_studio_save',$studio)[0]===200,'admin deactivates studio');
 [, $directory]=callApi('client','studios');check(!array_filter($directory['studios'],fn($s)=>$s['id']===$studioId),'inactive studio is hidden from clients');
 [$code,$custom]=callApi('admin','admin_style_save',['name'=>$tag.' Lash','type'=>'Wispy','description'=>'Custom catalog style','is_active'=>true]);check($code===200,'admin creates custom lash style');$extraStyleId=$custom['id'];
 check(callApi('admin','admin_style_save',['name'=>$tag.' Lash','type'=>'Wispy','description'=>'Duplicate','is_active'=>true])[0]===409,'duplicate style names are rejected');
 check(callApi('admin','admin_style_save',['id'=>$extraStyleId,'description'=>'Invalid image','image_data'=>'data:image/png;base64,AAAA'])[0]===422,'invalid uploaded image is rejected');
 check(callApi('client','save_favorites',['kind'=>'looks','items'=>[$tag.' Lash']])[0]===200,'custom style can be saved by client');
 check(callApi('admin','admin_studio_services',['id'=>$studioId,'is_active'=>false,'specialties'=>[$tag.' Lash','Classic']])[0]===200,'studio supports custom style before rename');
 check(callApi('admin','admin_style_save',['id'=>$extraStyleId,'description'=>'Updated custom style','name'=>$tag.' Renamed'])[0]===200,'admin edits custom style');
 check(callApi('client','session')[1]['saved']['looks']===[$tag.' Renamed'],'saved style follows renamed catalog item');
 [, $renamedSnapshot]=callApi('admin','admin_data');
 $renamedStudio=array_values(array_filter($renamedSnapshot['studios'],fn($s)=>$s['id']===$studioId))[0];
 check($renamedStudio['specialties']===[$tag.' Renamed','Classic'],'studio services follow renamed custom style');
 check(callApi('admin','admin_studio_save',array_replace($studio,['specialties'=>$renamedStudio['specialties']]))[0]===200,'studio remains editable after style rename');
 check(callApi('admin','admin_style_save',['id'=>$extraStyleId,'description'=>'Inactive style','is_active'=>false])[0]===200,'admin deactivates custom style');
 check(callApi('client','session')[1]['saved']['looks']===[],'inactive custom style is hidden from client favorites');
 [, $inactiveSnapshot]=callApi('admin','admin_data');
 $inactiveSaved=array_values(array_filter($inactiveSnapshot['saved'],fn($s)=>(int)$s['user_id']===$clientId&&$s['kind']==='looks'));
 check(count($inactiveSaved)===1&&!$inactiveSaved[0]['available'],'admin marks inactive saved looks unavailable');
 check(callApi('admin','admin_style_delete',['id'=>$extraStyleId])[0]===200,'admin removes custom style');$extraStyleId=null;
 [, $deletedSnapshot]=callApi('admin','admin_data');
 $deletedStudio=array_values(array_filter($deletedSnapshot['studios'],fn($s)=>$s['id']===$studioId))[0];
 check($deletedStudio['specialties']===['Classic'],'style deletion removes only the matching studio service');
 check(callApi('admin','admin_studio_save',array_replace($studio,['specialties'=>$deletedStudio['specialties']]))[0]===200,'studio remains editable after style deletion');
 callApi('client','save_favorites',['kind'=>'looks','items'=>['Wispy']]);
 check(callApi('admin','admin_password_save',['current_password'=>'wrong-password','password'=>'New-Admin-Password-123'])[0]===422,'password change verifies current password');
 check(callApi('admin','admin_password_save',['current_password'=>$password,'password'=>'New-Admin-Password-123'])[0]===200,'admin password change is persisted');
 $q=$db->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$ids[1]]);check(password_verify('New-Admin-Password-123',$q->fetchColumn()),'updated admin password uses a valid hash');
 check(callApi('admin','admin_user_status',['id'=>2147483647,'is_active'=>false])[0]===404,'missing user update is rejected');
 check(callApi('admin','admin_user_status',['id'=>$ids[1],'is_active'=>false])[0]===422,'administrator cannot be deactivated as a client');
 check(callApi('admin','admin_style_save',['id'=>2147483647,'description'=>'missing'])[0]===404,'missing style update is rejected');
 check(callApi('admin','admin_style_delete',['id'=>$originalStyle['id']])[0]===422,'core quiz styles cannot be deleted');
 check(callApi('admin','admin_studio_services',['id'=>$studioId,'is_active'=>false,'specialties'=>['Classic'],'colors'=>['Brown'],'customizations'=>['Color Accent'],'services'=>['Lash Lift']])[0]===200,'studio capabilities save to database');
 [, $adminSnapshot]=callApi('admin','admin_data');[, $clientDirectory]=callApi('client','studios');
 check($adminSnapshot['summary']['active_studios']===count($clientDirectory['studios']),'admin studio total equals client-visible Cavite directory');
 $updated=array_values(array_filter($adminSnapshot['studios'],fn($s)=>$s['id']===$studioId))[0];
 check($updated['specialties']===['Classic']&&$updated['capabilities']['colors']===['Brown'],'saved studio services and colors reload');
 check(callApi('admin','admin_studio_services',['id'=>$studioId,'is_active'=>false,'specialties'=>['Unknown']])[0]===422,'unknown studio services are rejected');
 check(callApi('admin','admin_style_save',['id'=>$originalStyle['id'],'description'=>'Updated from admin integration check.'])[0]===200,'admin edits style description');
 [, $catalog]=callApi('client','catalog');check($catalog['styles'][0]['description']==='Updated from admin integration check.','client receives updated style description');
 callApi('admin','admin_user_status',['id'=>$clientId,'is_active'=>false]);check(callApi('client','matches')[0]===401,'deactivation revokes existing client session');
 check(callApi('client','login',['email'=>$tag.'@example.com','password'=>$password])[0]===403,'inactive account cannot sign in');
 callApi('admin','admin_user_status',['id'=>$clientId,'is_active'=>true]);check(callApi('client','login',['email'=>$tag.'@example.com','password'=>$password])[0]===200,'reactivated client can sign in');
 [, $session]=callApi('client','session');check($session['saved']['looks']===['Wispy'],'favorites survive a new login');
 check($session['journey']['quizCount']===1 && $session['journey']['triedOn'],'progress survives a new login');
 check(callApi('admin','session')[1]['journey']===['quizCount'=>0,'triedOn'=>false,'events'=>[]],'activity does not leak to another account');
 check($session['saved']['studios']===[],'inactive studio is excluded from saved items');
 callApi('admin','logout',[]);check(callApi('admin','admin_data')[0]===401,'logout ends admin access');
 echo "Verified $checks integration checks.\n";
}finally{
 $q=$db->prepare('UPDATE recommendation_rules SET finish=? WHERE volume=?');foreach($originalRules as $volume=>$finish)$q->execute([$finish,$volume]);
 $db->prepare('UPDATE lash_styles SET description=? WHERE id=?')->execute([$originalStyle['description'],$originalStyle['id']]);
 if($extraStyleId)$db->prepare('DELETE FROM lash_styles WHERE id=?')->execute([$extraStyleId]);
 foreach($ids as $id)$db->prepare('DELETE FROM users WHERE id=? AND email LIKE ?')->execute([$id,$tag.'%']);
 if($studioId)$db->prepare('DELETE FROM studios WHERE id=? AND name=?')->execute([$studioId,$studio['name']]);
 foreach($cookies as $file)if(is_file($file))unlink($file);
 echo "Removed temporary test records; restored rules and style description.\n";
}
